// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXM4qtZKrpU1SiQw_lbbCwLXg9CIgF2XY',
    appId: '1:516529666958:web:f6ab283ce9cb249b5642df',
    messagingSenderId: '516529666958',
    projectId: 'my-tiktokclone-project',
    authDomain: 'my-tiktokclone-project.firebaseapp.com',
    storageBucket: 'my-tiktokclone-project.appspot.com',
    measurementId: 'G-83FP46Y29G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaQc0J5fTCIRRUjgF7turMRToK_iFJoT4',
    appId: '1:516529666958:android:51d270515980b0875642df',
    messagingSenderId: '516529666958',
    projectId: 'my-tiktokclone-project',
    storageBucket: 'my-tiktokclone-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhWzMK6CKGgBcaULqspMx6RWIo_MPdEs',
    appId: '1:516529666958:ios:758f46d70fe5324a5642df',
    messagingSenderId: '516529666958',
    projectId: 'my-tiktokclone-project',
    storageBucket: 'my-tiktokclone-project.appspot.com',
    iosBundleId: 'com.example.tiktokclonepractice',
  );
}
